import type { SignalCluster, Transaction, TrendPoint } from "./types";

export const trend: TrendPoint[] = [
  { day: "Thu", flagged: 42, highRisk: 6 },
  { day: "Fri", flagged: 55, highRisk: 8 },
  { day: "Sat", flagged: 51, highRisk: 7 },
  { day: "Sun", flagged: 68, highRisk: 12 },
  { day: "Mon", flagged: 77, highRisk: 13 },
  { day: "Tue", flagged: 91, highRisk: 16 },
  { day: "Wed", flagged: 106, highRisk: 19 },
];
export const transactions: Transaction[] = [
  {
    id: "TX-9084",
    corridor: "GCC -> Baltics",
    type: "Outbound wire",
    maskedAccount: "ACCT-7741-XX92",
    maskedBeneficiary: "BEN-44XX-8091",
    exposureUsd: 740000,
    riskScore: 94,
    riskLevel: "Critical",
    status: "Escalated",
    assignedTeam: "Sanctions queue",
    slaHoursRemaining: -4,
    openedAt: "2026-06-17T08:10:00+04:00",
    reasons: [
      "Sanctions watchlist proximity inside configured review threshold",
      "New beneficiary added less than 48 hours before payment initiation",
      "Amount exceeds corridor threshold exception policy",
    ],
    recommendedAction: "Escalate to sanctions team",
    coordinates: { x: 66, y: 26 },
  },
  {
    id: "TX-9051",
    corridor: "UK -> MENA",
    type: "Outbound wire",
    maskedAccount: "ACCT-2198-XX33",
    maskedBeneficiary: "BEN-12XX-4410",
    exposureUsd: 420000,
    riskScore: 88,
    riskLevel: "High",
    status: "In Review",
    assignedTeam: "Financial crime",
    slaHoursRemaining: 2,
    openedAt: "2026-06-17T09:35:00+04:00",
    reasons: [
      "Dormant account reactivated after extended inactivity",
      "Payment velocity above customer profile baseline",
      "High-risk corridor configured for enhanced review",
    ],
    recommendedAction: "Review KYC profile",
    coordinates: { x: 38, y: 60 },
  },
  {
    id: "TX-9036",
    corridor: "EU -> LATAM",
    type: "Outbound wire",
    maskedAccount: "ACCT-6640-XX18",
    maskedBeneficiary: "BEN-98XX-1267",
    exposureUsd: 315000,
    riskScore: 81,
    riskLevel: "High",
    status: "New",
    assignedTeam: "Operations review",
    slaHoursRemaining: 5,
    openedAt: "2026-06-17T10:45:00+04:00",
    reasons: [
      "Transaction amount exceeds normal customer threshold",
      "Unusual velocity detected across linked accounts",
      "Beneficiary relationship lacks recent supporting evidence",
    ],
    recommendedAction: "Request source of funds",
    coordinates: { x: 74, y: 70 },
  },
  {
    id: "TX-8998",
    corridor: "US -> APAC",
    type: "ACH transfer",
    maskedAccount: "ACCT-3190-XX55",
    maskedBeneficiary: "BEN-21XX-7782",
    exposureUsd: 288000,
    riskScore: 72,
    riskLevel: "Elevated",
    status: "Cleared",
    assignedTeam: "Manager review",
    slaHoursRemaining: 9,
    openedAt: "2026-06-16T17:28:00+04:00",
    reasons: [
      "High-risk corridor indicator triggered enhanced review",
      "Transaction cleared with documented manager rationale",
    ],
    recommendedAction: "Clear with manager note",
    coordinates: { x: 27, y: 38 },
  },
  {
    id: "TX-8972",
    corridor: "GCC -> East Africa",
    type: "Outbound wire",
    maskedAccount: "ACCT-8820-XX74",
    maskedBeneficiary: "BEN-56XX-9022",
    exposureUsd: 236000,
    riskScore: 69,
    riskLevel: "Elevated",
    status: "Blocked",
    assignedTeam: "KYC refresh",
    slaHoursRemaining: -1,
    openedAt: "2026-06-16T14:02:00+04:00",
    reasons: [
      "New beneficiary added without complete ownership evidence",
      "KYC refresh required before disposition can be recorded",
    ],
    recommendedAction: "Refresh beneficiary evidence",
    coordinates: { x: 54, y: 77 },
  },
  {
    id: "TX-8964",
    corridor: "MENA -> EU",
    type: "Internal transfer",
    maskedAccount: "ACCT-4522-XX01",
    maskedBeneficiary: "BEN-87XX-3104",
    exposureUsd: 184000,
    riskScore: 62,
    riskLevel: "Moderate",
    status: "In Review",
    assignedTeam: "Financial crime",
    slaHoursRemaining: 11,
    openedAt: "2026-06-16T11:15:00+04:00",
    reasons: [
      "Corridor configured for periodic enhanced monitoring",
      "Review requested due to recent beneficiary metadata change",
    ],
    recommendedAction: "Review KYC profile",
    coordinates: { x: 44, y: 44 },
  },
];

export const signalClusters: SignalCluster[] = [
  {
    name: "Watchlist proximity",
    count: 18,
    severity: "Critical",
    summary: "Open reviews across four corridors require sanctions-team attention.",
  },
  {
    name: "Unusual velocity",
    count: 42,
    severity: "High",
    summary: "Transaction frequency is above customer profile baseline.",
  },
  {
    name: "Dormant reactivation",
    count: 11,
    severity: "High",
    summary: "Previously inactive accounts initiated new outbound movement.",
  },
  {
    name: "New beneficiary",
    count: 36,
    severity: "Elevated",
    summary: "Beneficiary additions occurred within 72 hours of payment attempts.",
  },
  {
    name: "Threshold exception",
    count: 25,
    severity: "Elevated",
    summary: "Amounts exceeded configured corridor and customer thresholds.",
  },
];
